"""Remove unique constraint on session_name

Revision ID: 0f5eff6f27c9
Revises: b47da8f2fc43
Create Date: 2025-06-06 00:05:39.558917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5eff6f27c9'
down_revision = 'b47da8f2fc43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('uq_user_session')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('uq_user_session', ['user_id', 'session_name'], unique=True)

    # ### end Alembic commands ###
