"""Initial schema

Revision ID: 3e9420da3289
Revises: 
Create Date: 2025-05-01 19:06:50.168790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9420da3289'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('topic_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('signature', sa.String(length=256), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.String(length=10), nullable=False),
    sa.Column('text', sa.String(length=512), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('audio_url', sa.String(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('session_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('user_id', 'session_name', name='uq_user_session')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('idx_sessions_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('practice_records',
    sa.Column('record_id', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('session_id', sa.String(length=10), nullable=False),
    sa.Column('question_id', sa.String(length=10), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('user_audio_key', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    with op.batch_alter_table('practice_records', schema=None) as batch_op:
        batch_op.create_index('idx_practice_session_time', ['session_id', 'attempted_at'], unique=False)
        batch_op.create_index('idx_practice_user_time', ['user_id', 'attempted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_records', schema=None) as batch_op:
        batch_op.drop_index('idx_practice_user_time')
        batch_op.drop_index('idx_practice_session_time')

    op.drop_table('practice_records')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_sessions_user_created')

    op.drop_table('sessions')
    op.drop_table('questions')
    op.drop_table('users')
    op.drop_table('topics')
    # ### end Alembic commands ###
