"""Add last_active_at column to sessions

Revision ID: 49e1759674ec
Revises: d7608bf83ee1
Create Date: 2025-05-03 01:09:50.827947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e1759674ec'
down_revision = 'd7608bf83ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_active_at', sa.DateTime(), nullable=False))
        batch_op.drop_index('idx_sessions_user_created')
        batch_op.create_index('idx_sessions_user_last_active', ['user_id', 'last_active_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_sessions_user_last_active')
        batch_op.create_index('idx_sessions_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.drop_column('last_active_at')

    # ### end Alembic commands ###
