"""Add summary scores to practice_records

Revision ID: b47da8f2fc43
Revises: 49e1759674ec
Create Date: 2025-05-05 12:40:16.242538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b47da8f2fc43'
down_revision = '49e1759674ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accuracy_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('fluency_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('integrity_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('standard_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_score', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_records', schema=None) as batch_op:
        batch_op.drop_column('total_score')
        batch_op.drop_column('standard_score')
        batch_op.drop_column('integrity_score')
        batch_op.drop_column('fluency_score')
        batch_op.drop_column('accuracy_score')

    # ### end Alembic commands ###
